language: node_js
node_js:
  - 10 # use nodejs v10 LTS	  - 10 # use nodejs v10 LTS

cache: npm
branches:	branches:
  only:	  only:
    - hexo-project	    - hexo-project # build master branch only

install:	
- npm ci	
# keep the npm cache around to speed up installs	
cache:	
  directories:	
  - "$HOME/.npm"	

script:	script:
  - hexo generate # generate static files	  - hexo generate # generate static files

deploy:	deploy:
  provider: pages	  provider: pages
  skip-cleanup: true